
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-06
owner: ucsb-cs156-f25
repo_name: team02-f25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY3MDI5MzIw","is_bot":false,"login":"andrewzshen","name":"Andrew Shen"},"headRefName":"andrew-helprequest-integration-test","number":125,"title":"Integration test for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/125"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"longjiao-integration-test","number":124,"title":"Longjiao integration test","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/124"}]
