
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-06
owner: ucsb-cs156-f25
repo_name: team02-f25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY3MDI5MzIw","is_bot":false,"login":"andrewzshen","name":"Andrew Shen"},"headRefName":"andrew-helprequest-table-component","number":108,"title":"Passed mutation tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/108"},{"author":{"id":"U_kgDOCVy2iQ","is_bot":false,"login":"AbhiramA02","name":""},"headRefName":"aa-RecommendationRequests-index-page","number":107,"title":"aa  - recommendation requests index page","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/107"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-index-page","number":99,"title":"jml - MenuItemReview index page, also fixed formatting","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/99"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-edit-page","number":98,"title":"jml - add MenuItemReview edit page","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/98"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-MenuItemReview-create-page","number":85,"title":"jml - MenuItemReview create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-06/pull/85"}]
